FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker ./cmd/analytics_worker

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/worker .
COPY --from=builder /app/migrations ./migrations

CMD ["./worker"]